version: "3.4"

services:
    app:
        build:
            context: .
            target: dev
        volumes:
            - ./:/app
            - ./conf/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
        extra_hosts:
            - host.docker.internal:host-gateway
        tty: true
